-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 18:48:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`OFFY_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OFFY_CONFIG` (
  `COD_CONFIG` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`COD_CONFIG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `COD_USUARIO` INT(11) NOT NULL,
  `DES_USUARIO` VARCHAR(100) NULL,
  `DES_EMAIL` VARCHAR(100) NULL,
  `DES_SENHA` VARCHAR(100) NULL,
  `TIP_ADMIN` TINYINT(1) NULL,
  `TIP_STATUS` TINYINT(1) NULL,
  PRIMARY KEY (`COD_USUARIO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
